#!/usr/bin/env python

import collections
import math

import util

MIN_SELL = 1000000  # minimum sale value for an item to be shown
MIN_MARGIN = 50  # minimum margin for an item to be shown

DIV = '+{}+'.format('+'.join(['-' * width for width in (60, 20, 20, 20, 30, 30)]))
LINE = '| {:<58} | {:>18} | {:>18} | {:>18} | {:>28} | {:>28} |'

# from https://www.adam4eve.eu/info_stations.php
#
# Perimeter = 1044752365771
# Ashab = 1044857068649
# Botane = 1044961079041

JITA = 60003760
AMARR = 60008494
DODIXIE = 60011866

STATIONS = collections.OrderedDict((
  (JITA, 'Jita'),
  (AMARR, 'Amarr'),
  (DODIXIE, 'Dodixie'),
))

# from https://www.adam4eve.eu/info_types.php

MINERALS = collections.OrderedDict((
  ('Tritanium', 34),
  ('Pyerite', 35),
  ('Mexallon', 36),
  ('Isogen', 37),
  ('Nocxium', 38),
  ('Zydrine', 39),
  ('Megacyte', 40),
  ('Morphite', 11399),
))


# Skills from the LP stores (hence no direct NPC sellers).

SKILLS = collections.OrderedDict((
  ('Mining Connections', 3893),
  ('Distribution Connections', 3894),
  ('Security Connections', 3895),

  ('Small Artillery Specialization', 12201),
  ('Medium Artillery Specialization', 12202),
  ('Large Artillery Specialization', 12203),
  ('Capital Artillery Specialization', 41404),

  ('Small Autocannon Specialization', 11084),
  ('Medium Autocannon Specialization', 12208),
  ('Large Autocannon Specialization', 12209),
  ('Capital Autocannon Specialization', 41403),

  ('Small Beam Laser Specialization', 11083),
  ('Medium Beam Laser Specialization', 12204),
  ('Large Beam Laser Specialization', 12205),
  ('Capital Beam Laser Specialization', 41408),

  ('Small Blaster Specialization', 12210),
  ('Medium Blaster Specialization', 12211),
  ('Large Blaster Specialization', 12212),
  ('Capital Blaster Specialization', 41405),

  ('Small Pulse Laser Specialization', 12213),
  ('Medium Pulse Laser Specialization', 12214),
  ('Large Pulse Laser Specialization', 12215),
  ('Capital Pulse Laser Specialization', 41407),

  ('Amarr Drone Specialization', 12484),
  ('Minmatar Drone Specialization', 12485),
  ('Gallente Drone Specialization', 12486),
  ('Caldari Drone Specialization', 12487),

  ('Small Disintegrator Specialization', 47873),
  ('Medium Disintegrator Specialization', 47874),
  ('Large Disintegrator Specialization', 47875),

  ('Small Vorton Specialization', 54827),
  ('Medium Vorton Specialization', 54828),
  ('Large Vorton Specialization', 54829),
))

# High tier abyssal filaments.

FILAMENTS = collections.OrderedDict((
  ('Cataclysmic Dark Filament', 56140),
  ('Cataclysmic Electrical Filament', 56139),
  ('Cataclysmic Exotic Filament', 56141),
  ('Cataclysmic Firestorm Filament', 56142),
  ('Cataclysmic Gamma Filament', 56143),
  ('Chaotic Dark Filament', 47895),
  ('Chaotic Electrical Filament', 47907),
  ('Chaotic Exotic Filament', 47891),
  ('Chaotic Firestorm Filament', 47899),
  ('Chaotic Gamma Filament', 47903),
  ('Fierce Dark Filament', 47893),
  ('Fierce Electrical Filament', 47905),
  ('Fierce Exotic Filament', 47889),
  ('Fierce Firestorm Filament', 47897),
  ('Fierce Gamma Filament', 47901),
  ('Raging Dark Filament', 47894),
  ('Raging Electrical Filament', 47906),
  ('Raging Exotic Filament', 47890),
  ('Raging Firestorm Filament', 47898),
  ('Raging Gamma Filament', 47902),
))

FACTION_MODULES = collections.OrderedDict((
  ('Centus X-Type EM Armor Hardener', 18935),
  ('Centus X-Type Explosive Armor Hardener', 18939),
  ('Centus X-Type Kinetic Armor Hardener', 18943),
  ('Centus X-Type Large Armor Repairer', 19046),
  ('Centus X-Type Thermal Armor Hardener', 18947),
  ('Core X-Type 100MN Afterburner', 18698),
  ('Core X-Type 500MN Microwarpdrive', 19335),
  ('Core X-Type EM Armor Hardener', 18973),
  ('Core X-Type Explosive Armor Hardener', 18975),
  ('Core X-Type Kinetic Armor Hardener', 18977),
  ('Core X-Type Large Armor Repairer', 19038),
  ('Core X-Type Thermal Armor Hardener', 18979),
  ('Corpus X-Type EM Armor Hardener', 18933),
  ('Corpus X-Type Explosive Armor Hardener', 18937),
  ('Corpus X-Type Heavy Energy Neutralizer', 37631),
  ('Corpus X-Type Heavy Energy Nosferatu', 19119),
  ('Corpus X-Type Kinetic Armor Hardener', 18941),
  ('Corpus X-Type Large Armor Repairer', 19045),
  ('Corpus X-Type Thermal Armor Hardener', 18945),
  ('Gist X-Type 100MN Afterburner', 18676),
  ('Gist X-Type 500MN Microwarpdrive', 19359),
  ('Gist X-Type EM Shield Hardener', 19281),
  ('Gist X-Type Explosive Shield Hardener', 19285),
  ('Gist X-Type Kinetic Shield Hardener', 19287),
  ('Gist X-Type Large Shield Booster', 19200),
  ('Gist X-Type Shield Boost Amplifier', 19301),
  ('Gist X-Type Thermal Shield Hardener', 19283),
  ('Gist X-Type X-Large Shield Booster', 19198),
  ('Pith X-Type EM Shield Hardener', 19282),
  ('Pith X-Type Explosive Shield Hardener', 19286),
  ('Pith X-Type Kinetic Shield Hardener', 19288),
  ('Pith X-Type Large Shield Booster', 19207),
  ('Pith X-Type Shield Boost Amplifier', 19295),
  ('Pith X-Type Thermal Shield Hardener', 19284),
  ('Pith X-Type X-Large Shield Booster', 19208),

  ('Centii A-Type EM Coating', 18762),
  ('Centii A-Type Explosive Coating', 18758),
  ('Centii A-Type Kinetic Coating', 18754),
  ('Centii A-Type Multispectrum Coating', 18710),
  ('Centii A-Type Small Armor Repairer', 19009),
  ('Centii A-Type Small Remote Armor Repairer', 19051),
  ('Centii A-Type Small Remote Capacitor Transmitter', 19075),
  ('Centii A-Type Thermal Coating', 18766),
  ('Centum A-Type EM Energized Membrane', 18871),
  ('Centum A-Type Explosive Energized Membrane', 18875),
  ('Centum A-Type Kinetic Energized Membrane', 18879),
  ('Centum A-Type Medium Armor Repairer', 19027),
  ('Centum A-Type Medium Remote Armor Repairer', 19057),
  ('Centum A-Type Medium Remote Capacitor Transmitter', 19087),
  ('Centum A-Type Multispectrum Energized Membrane', 18883),
  ('Centum A-Type Thermal Energized Membrane', 18867),
  ('Centus A-Type EM Armor Hardener', 18931),
  ('Centus A-Type Explosive Armor Hardener', 18927),
  ('Centus A-Type Kinetic Armor Hardener', 18923),
  ('Centus A-Type Large Armor Repairer', 19044),
  ('Centus A-Type Thermal Armor Hardener', 18919),
  ('Core A-Type 100MN Afterburner', 18696),
  ('Core A-Type 500MN Microwarpdrive', 19329),
  ('Core A-Type EM Armor Hardener', 18965),
  ('Core A-Type Explosive Armor Hardener', 18967),
  ('Core A-Type Kinetic Armor Hardener', 18969),
  ('Core A-Type Large Armor Repairer', 19037),
  ('Core A-Type Thermal Armor Hardener', 18971),
  ('Coreli A-Type 1MN Afterburner', 18692),
  ('Coreli A-Type 5MN Microwarpdrive', 19325),
  ('Coreli A-Type EM Coating', 18795),
  ('Coreli A-Type Explosive Coating', 18793),
  ('Coreli A-Type Kinetic Coating', 18791),
  ('Coreli A-Type Multispectrum Coating', 18789),
  ('Coreli A-Type Small Armor Repairer', 19015),
  ('Coreli A-Type Small Remote Armor Repairer', 18985),
  ('Coreli A-Type Thermal Coating', 18797),
  ('Corelum A-Type 10MN Afterburner', 18694),
  ('Corelum A-Type 50MN Microwarpdrive', 19327),
  ('Corelum A-Type EM Energized Membrane', 18825),
  ('Corelum A-Type Explosive Energized Membrane', 18823),
  ('Corelum A-Type Kinetic Energized Membrane', 18821),
  ('Corelum A-Type Medium Armor Repairer', 19033),
  ('Corelum A-Type Medium Remote Armor Repairer', 18991),
  ('Corelum A-Type Multispectrum Energized Membrane', 18819),
  ('Corelum A-Type Thermal Energized Membrane', 18827),
  ('Corpii A-Type EM Coating', 18760),
  ('Corpii A-Type Explosive Coating', 18756),
  ('Corpii A-Type Kinetic Coating', 18752),
  ('Corpii A-Type Multispectrum Coating', 18708),
  ('Corpii A-Type Small Armor Repairer', 19003),
  ('Corpii A-Type Small Energy Neutralizer', 37624),
  ('Corpii A-Type Small Energy Nosferatu', 19105),
  ('Corpii A-Type Small Remote Capacitor Transmitter', 19069),
  ('Corpii A-Type Thermal Coating', 18764),
  ('Corpum A-Type EM Energized Membrane', 18869),
  ('Corpum A-Type Explosive Energized Membrane', 18873),
  ('Corpum A-Type Kinetic Energized Membrane', 18877),
  ('Corpum A-Type Medium Armor Repairer', 19021),
  ('Corpum A-Type Medium Energy Neutralizer', 37627),
  ('Corpum A-Type Medium Energy Nosferatu', 19111),
  ('Corpum A-Type Medium Remote Capacitor Transmitter', 19081),
  ('Corpum A-Type Multispectrum Energized Membrane', 18881),
  ('Corpum A-Type Thermal Energized Membrane', 18865),
  ('Corpus A-Type EM Armor Hardener', 18929),
  ('Corpus A-Type Explosive Armor Hardener', 18925),
  ('Corpus A-Type Heavy Energy Neutralizer', 37630),
  ('Corpus A-Type Heavy Energy Nosferatu', 19117),
  ('Corpus A-Type Kinetic Armor Hardener', 18921),
  ('Corpus A-Type Large Armor Repairer', 19043),
  ('Corpus A-Type Thermal Armor Hardener', 18917),
  ('Gist A-Type 100MN Afterburner', 18674),
  ('Gist A-Type 500MN Microwarpdrive', 19353),
  ('Gist A-Type EM Shield Hardener', 19279),
  ('Gist A-Type Explosive Shield Hardener', 19275),
  ('Gist A-Type Kinetic Shield Hardener', 19273),
  ('Gist A-Type Large Shield Booster', 19199),
  ('Gist A-Type Shield Boost Amplifier', 19293),
  ('Gist A-Type Thermal Shield Hardener', 19277),
  ('Gist A-Type X-Large Shield Booster', 19197),
  ('Gistii A-Type 1MN Afterburner', 18670),
  ('Gistii A-Type 5MN Microwarpdrive', 19349),
  ('Gistii A-Type Small Remote Shield Booster', 19133),
  ('Gistii A-Type Small Shield Booster', 19173),
  ('Gistum A-Type 10MN Afterburner', 18672),
  ('Gistum A-Type 50MN Microwarpdrive', 19351),
  ('Gistum A-Type EM Shield Amplifier', 19255),
  ('Gistum A-Type Explosive Shield Amplifier', 19249),
  ('Gistum A-Type Kinetic Shield Amplifier', 19253),
  ('Gistum A-Type Medium Remote Shield Booster', 19145),
  ('Gistum A-Type Medium Shield Booster', 19185),
  ('Gistum A-Type Multispectrum Shield Hardener', 4346),
  ('Gistum A-Type Thermal Shield Amplifier', 19251),
  ('Pith A-Type EM Shield Hardener', 19280),
  ('Pith A-Type Explosive Shield Hardener', 19276),
  ('Pith A-Type Kinetic Shield Hardener', 19274),
  ('Pith A-Type Large Shield Booster', 19205),
  ('Pith A-Type Shield Boost Amplifier', 19311),
  ('Pith A-Type Thermal Shield Hardener', 19278),
  ('Pith A-Type X-Large Shield Booster', 19206),
  ('Pithi A-Type Small Remote Shield Booster', 19139),
  ('Pithi A-Type Small Shield Booster', 19179),
  ('Pithum A-Type EM Shield Amplifier', 19231),
  ('Pithum A-Type Explosive Shield Amplifier', 19225),
  ('Pithum A-Type Kinetic Shield Amplifier', 19229),
  ('Pithum A-Type Medium Remote Shield Booster', 19151),
  ('Pithum A-Type Medium Shield Booster', 19191),
  ('Pithum A-Type Multispectrum Shield Hardener', 4347),
  ('Pithum A-Type Thermal Shield Amplifier', 19227),

  ('Centii B-Type EM Coating', 18750),
  ('Centii B-Type Explosive Coating', 18746),
  ('Centii B-Type Kinetic Coating', 18742),
  ('Centii B-Type Multispectrum Coating', 18706),
  ('Centii B-Type Small Armor Repairer', 19007),
  ('Centii B-Type Small Remote Armor Repairer', 19049),
  ('Centii B-Type Small Remote Capacitor Transmitter', 19073),
  ('Centii B-Type Thermal Coating', 18730),
  ('Centum B-Type EM Energized Membrane', 19363),
  ('Centum B-Type Explosive Energized Membrane', 18859),
  ('Centum B-Type Kinetic Energized Membrane', 18855),
  ('Centum B-Type Medium Armor Repairer', 19025),
  ('Centum B-Type Medium Remote Armor Repairer', 19055),
  ('Centum B-Type Medium Remote Capacitor Transmitter', 19085),
  ('Centum B-Type Multispectrum Energized Membrane', 18851),
  ('Centum B-Type Thermal Energized Membrane', 18863),
  ('Centus B-Type EM Armor Hardener', 18903),
  ('Centus B-Type Explosive Armor Hardener', 18907),
  ('Centus B-Type Kinetic Armor Hardener', 18911),
  ('Centus B-Type Large Armor Repairer', 19042),
  ('Centus B-Type Thermal Armor Hardener', 18915),
  ('Core B-Type 100MN Afterburner', 18690),
  ('Core B-Type 500MN Microwarpdrive', 19323),
  ('Core B-Type EM Armor Hardener', 18957),
  ('Core B-Type Explosive Armor Hardener', 18959),
  ('Core B-Type Kinetic Armor Hardener', 18961),
  ('Core B-Type Large Armor Repairer', 19036),
  ('Core B-Type Thermal Armor Hardener', 18963),
  ('Coreli B-Type 1MN Afterburner', 18686),
  ('Coreli B-Type 5MN Microwarpdrive', 19319),
  ('Coreli B-Type EM Coating', 18785),
  ('Coreli B-Type Explosive Coating', 18783),
  ('Coreli B-Type Kinetic Coating', 18781),
  ('Coreli B-Type Multispectrum Coating', 18779),
  ('Coreli B-Type Small Armor Repairer', 19013),
  ('Coreli B-Type Small Remote Armor Repairer', 18983),
  ('Coreli B-Type Thermal Coating', 18787),
  ('Corelum B-Type 10MN Afterburner', 18688),
  ('Corelum B-Type 50MN Microwarpdrive', 19321),
  ('Corelum B-Type EM Energized Membrane', 18815),
  ('Corelum B-Type Explosive Energized Membrane', 18813),
  ('Corelum B-Type Kinetic Energized Membrane', 18811),
  ('Corelum B-Type Medium Armor Repairer', 19031),
  ('Corelum B-Type Medium Remote Armor Repairer', 18989),
  ('Corelum B-Type Multispectrum Energized Membrane', 18809),
  ('Corelum B-Type Thermal Energized Membrane', 18817),
  ('Corpii B-Type EM Coating', 18748),
  ('Corpii B-Type Explosive Coating', 18744),
  ('Corpii B-Type Kinetic Coating', 18740),
  ('Corpii B-Type Multispectrum Coating', 18704),
  ('Corpii B-Type Small Armor Repairer', 19001),
  ('Corpii B-Type Small Energy Neutralizer', 37623),
  ('Corpii B-Type Small Energy Nosferatu', 19103),
  ('Corpii B-Type Small Remote Capacitor Transmitter', 19067),
  ('Corpii B-Type Thermal Coating', 18728),
  ('Corpum B-Type EM Energized Membrane', 19361),
  ('Corpum B-Type Explosive Energized Membrane', 18857),
  ('Corpum B-Type Kinetic Energized Membrane', 18853),
  ('Corpum B-Type Medium Armor Repairer', 19019),
  ('Corpum B-Type Medium Energy Neutralizer', 37626),
  ('Corpum B-Type Medium Energy Nosferatu', 19109),
  ('Corpum B-Type Medium Remote Capacitor Transmitter', 19079),
  ('Corpum B-Type Multispectrum Energized Membrane', 18849),
  ('Corpum B-Type Thermal Energized Membrane', 18861),
  ('Corpus B-Type EM Armor Hardener', 18901),
  ('Corpus B-Type Explosive Armor Hardener', 18905),
  ('Corpus B-Type Heavy Energy Neutralizer', 37629),
  ('Corpus B-Type Heavy Energy Nosferatu', 19115),
  ('Corpus B-Type Kinetic Armor Hardener', 18909),
  ('Corpus B-Type Large Armor Repairer', 19041),
  ('Corpus B-Type Thermal Armor Hardener', 18913),
  ('Gist B-Type 100MN Afterburner', 18668),
  ('Gist B-Type 500MN Microwarpdrive', 19347),
  ('Gist B-Type EM Shield Hardener', 19265),
  ('Gist B-Type Explosive Shield Hardener', 19269),
  ('Gist B-Type Kinetic Shield Hardener', 19271),
  ('Gist B-Type Large Shield Booster', 19194),
  ('Gist B-Type Shield Boost Amplifier', 19299),
  ('Gist B-Type Thermal Shield Hardener', 19267),
  ('Gist B-Type X-Large Shield Booster', 19196),
  ('Gistii B-Type 1MN Afterburner', 18664),
  ('Gistii B-Type 5MN Microwarpdrive', 19343),
  ('Gistii B-Type Small Remote Shield Booster', 19131),
  ('Gistii B-Type Small Shield Booster', 19171),
  ('Gistum B-Type 10MN Afterburner', 18666),
  ('Gistum B-Type 50MN Microwarpdrive', 19345),
  ('Gistum B-Type EM Shield Amplifier', 19247),
  ('Gistum B-Type Explosive Shield Amplifier', 19235),
  ('Gistum B-Type Kinetic Shield Amplifier', 19243),
  ('Gistum B-Type Medium Remote Shield Booster', 19143),
  ('Gistum B-Type Medium Shield Booster', 19183),
  ('Gistum B-Type Multispectrum Shield Hardener', 4345),
  ('Gistum B-Type Thermal Shield Amplifier', 19239),
  ('Pith B-Type EM Shield Hardener', 19266),
  ('Pith B-Type Explosive Shield Hardener', 19270),
  ('Pith B-Type Kinetic Shield Hardener', 19272),
  ('Pith B-Type Large Shield Booster', 19203),
  ('Pith B-Type Shield Boost Amplifier', 19303),
  ('Pith B-Type Thermal Shield Hardener', 19268),
  ('Pith B-Type X-Large Shield Booster', 19204),
  ('Pithi B-Type Small Remote Shield Booster', 19137),
  ('Pithi B-Type Small Shield Booster', 19177),
  ('Pithum B-Type EM Shield Amplifier', 19223),
  ('Pithum B-Type Explosive Shield Amplifier', 19217),
  ('Pithum B-Type Kinetic Shield Amplifier', 19221),
  ('Pithum B-Type Medium Remote Shield Booster', 19149),
  ('Pithum B-Type Medium Shield Booster', 19189),
  ('Pithum B-Type Multispectrum Shield Hardener', 4348),
  ('Pithum B-Type Thermal Shield Amplifier', 19219),

  ('Centii C-Type EM Coating', 18722),
  ('Centii C-Type Explosive Coating', 18718),
  ('Centii C-Type Kinetic Coating', 18714),
  ('Centii C-Type Multispectrum Coating', 18702),
  ('Centii C-Type Small Armor Repairer', 19005),
  ('Centii C-Type Small Remote Armor Repairer', 19047),
  ('Centii C-Type Small Remote Capacitor Transmitter', 19071),
  ('Centii C-Type Thermal Coating', 18726),
  ('Centum C-Type EM Energized Membrane', 18843),
  ('Centum C-Type Explosive Energized Membrane', 18839),
  ('Centum C-Type Kinetic Energized Membrane', 18835),
  ('Centum C-Type Medium Armor Repairer', 19023),
  ('Centum C-Type Medium Remote Armor Repairer', 19053),
  ('Centum C-Type Medium Remote Capacitor Transmitter', 19083),
  ('Centum C-Type Multispectrum Energized Membrane', 18831),
  ('Centum C-Type Thermal Energized Membrane', 18847),
  ('Centus C-Type EM Armor Hardener', 18887),
  ('Centus C-Type Explosive Armor Hardener', 18891),
  ('Centus C-Type Kinetic Armor Hardener', 18895),
  ('Centus C-Type Large Armor Repairer', 19040),
  ('Centus C-Type Thermal Armor Hardener', 18899),
  ('Core C-Type 100MN Afterburner', 18684),
  ('Core C-Type 500MN Microwarpdrive', 19317),
  ('Core C-Type EM Armor Hardener', 18949),
  ('Core C-Type Explosive Armor Hardener', 18951),
  ('Core C-Type Kinetic Armor Hardener', 18953),
  ('Core C-Type Large Armor Repairer', 19035),
  ('Core C-Type Thermal Armor Hardener', 18955),
  ('Coreli C-Type 1MN Afterburner', 18680),
  ('Coreli C-Type 5MN Microwarpdrive', 19313),
  ('Coreli C-Type EM Coating', 18775),
  ('Coreli C-Type Explosive Coating', 18772),
  ('Coreli C-Type Kinetic Coating', 18770),
  ('Coreli C-Type Multispectrum Coating', 18768),
  ('Coreli C-Type Small Armor Repairer', 19011),
  ('Coreli C-Type Small Remote Armor Repairer', 18981),
  ('Coreli C-Type Thermal Coating', 18777),
  ('Corelum C-Type 10MN Afterburner', 18682),
  ('Corelum C-Type 50MN Microwarpdrive', 19315),
  ('Corelum C-Type EM Energized Membrane', 18805),
  ('Corelum C-Type Explosive Energized Membrane', 18803),
  ('Corelum C-Type Kinetic Energized Membrane', 18801),
  ('Corelum C-Type Medium Armor Repairer', 19029),
  ('Corelum C-Type Medium Remote Armor Repairer', 18987),
  ('Corelum C-Type Multispectrum Energized Membrane', 18799),
  ('Corelum C-Type Thermal Energized Membrane', 18807),
  ('Corpii C-Type EM Coating', 18720),
  ('Corpii C-Type Explosive Coating', 18716),
  ('Corpii C-Type Kinetic Coating', 18712),
  ('Corpii C-Type Multispectrum Coating', 18700),
  ('Corpii C-Type Small Armor Repairer', 18999),
  ('Corpii C-Type Small Energy Neutralizer', 37622),
  ('Corpii C-Type Small Energy Nosferatu', 19101),
  ('Corpii C-Type Small Remote Capacitor Transmitter', 19065),
  ('Corpii C-Type Thermal Coating', 18724),
  ('Corpum C-Type EM Energized Membrane', 18841),
  ('Corpum C-Type Explosive Energized Membrane', 18837),
  ('Corpum C-Type Kinetic Energized Membrane', 18833),
  ('Corpum C-Type Medium Armor Repairer', 19017),
  ('Corpum C-Type Medium Energy Neutralizer', 37625),
  ('Corpum C-Type Medium Energy Nosferatu', 19107),
  ('Corpum C-Type Medium Remote Capacitor Transmitter', 19077),
  ('Corpum C-Type Multispectrum Energized Membrane', 18829),
  ('Corpum C-Type Thermal Energized Membrane', 18845),
  ('Corpus C-Type EM Armor Hardener', 18885),
  ('Corpus C-Type Explosive Armor Hardener', 18889),
  ('Corpus C-Type Heavy Energy Neutralizer', 37628),
  ('Corpus C-Type Heavy Energy Nosferatu', 19113),
  ('Corpus C-Type Kinetic Armor Hardener', 18893),
  ('Corpus C-Type Large Armor Repairer', 19039),
  ('Corpus C-Type Thermal Armor Hardener', 18897),
  ('Gist C-Type 100MN Afterburner', 18662),
  ('Gist C-Type 500MN Microwarpdrive', 19341),
  ('Gist C-Type EM Shield Hardener', 19263),
  ('Gist C-Type Explosive Shield Hardener', 19259),
  ('Gist C-Type Kinetic Shield Hardener', 19257),
  ('Gist C-Type Large Shield Booster', 19193),
  ('Gist C-Type Shield Boost Amplifier', 19297),
  ('Gist C-Type Thermal Shield Hardener', 19261),
  ('Gist C-Type X-Large Shield Booster', 19195),
  ('Gistii C-Type 1MN Afterburner', 18658),
  ('Gistii C-Type 5MN Microwarpdrive', 19337),
  ('Gistii C-Type Small Remote Shield Booster', 19129),
  ('Gistii C-Type Small Shield Booster', 19169),
  ('Gistum C-Type 10MN Afterburner', 18660),
  ('Gistum C-Type 50MN Microwarpdrive', 19339),
  ('Gistum C-Type EM Shield Amplifier', 19245),
  ('Gistum C-Type Explosive Shield Amplifier', 19233),
  ('Gistum C-Type Kinetic Shield Amplifier', 19241),
  ('Gistum C-Type Medium Remote Shield Booster', 19141),
  ('Gistum C-Type Medium Shield Booster', 19181),
  ('Gistum C-Type Multispectrum Shield Hardener', 2050),
  ('Gistum C-Type Thermal Shield Amplifier', 19237),
  ('Pith C-Type EM Shield Hardener', 19264),
  ('Pith C-Type Explosive Shield Hardener', 19260),
  ('Pith C-Type Kinetic Shield Hardener', 19258),
  ('Pith C-Type Large Shield Booster', 19201),
  ('Pith C-Type Shield Boost Amplifier', 19289),
  ('Pith C-Type Thermal Shield Hardener', 19262),
  ('Pith C-Type X-Large Shield Booster', 19202),
  ('Pithi C-Type Small Remote Shield Booster', 19135),
  ('Pithi C-Type Small Shield Booster', 19175),
  ('Pithum C-Type EM Shield Amplifier', 19215),
  ('Pithum C-Type Explosive Shield Amplifier', 19209),
  ('Pithum C-Type Kinetic Shield Amplifier', 19213),
  ('Pithum C-Type Medium Remote Shield Booster', 19147),
  ('Pithum C-Type Medium Shield Booster', 19187),
  ('Pithum C-Type Multispectrum Shield Hardener', 4349),
  ('Pithum C-Type Thermal Shield Amplifier', 19211),

  ('Dread Guristas Drone Damage Amplifier', 33846),
  ('Federation Navy Drone Damage Amplifier', 33842),
  ('Imperial Navy Drone Damage Amplifier', 33844),
  ('Sentient Drone Damage Amplifier', 33848),
))

# Additional items to consider.

EXTRA = collections.OrderedDict((
  ('Graviton Physics', 11446),
  ('High Energy Physics', 11433),
  ('Hydromagnetic Physics', 11443),
  ('Quantum Physics', 11455),
))


if __name__ == '__main__':
  prices = {}  # {item => {station => price}}
  items = MINERALS | SKILLS | FILAMENTS | FACTION_MODULES | EXTRA

  for station_id in STATIONS.keys():
    for price in util.get_prices(station_id, items.values()):
      prices.setdefault(price.item, {})[station_id] = price

  lines = []  # list of (item_name, item_id, buy_from, sell_at, margin) tuples

  for item_name, item_id in items.items():
    buy_from = sorted(prices[item_id].values(), key = lambda price: price.sell if price.sell else math.inf)[0]
    sell_at = sorted(prices[item_id].values(), key = lambda price: price.sell if price.sell else -1, reverse = True)[0]
    margin = int((sell_at.sell - buy_from.sell) / buy_from.sell * 100) if (buy_from.sell and sell_at.sell) else None
    has_shortage = prices[item_id][JITA].sell is None or prices[item_id][AMARR].sell is None or prices[item_id][DODIXIE].sell is None

    if has_shortage or (margin >= MIN_MARGIN and sell_at.sell >= MIN_SELL):
      lines.append((item_name, item_id, buy_from, sell_at, margin))

  lines.sort(key = lambda entry: entry[4] if entry[4] is not None else -1, reverse = True)

  headers = ('Item', 'Jita', 'Amarr', 'Dodixie', 'Buy from...', 'Sell at...')

  print(DIV)
  print(LINE.format(*headers))
  print(DIV)

  for item_name, item_id, buy_from, sell_at, margin in lines:
    print(LINE.format(
      item_name,
      '{:,}'.format(prices[item_id][JITA].sell) if prices[item_id][JITA].sell else 'N/A',
      '{:,}'.format(prices[item_id][AMARR].sell) if prices[item_id][AMARR].sell else 'N/A',
      '{:,}'.format(prices[item_id][DODIXIE].sell) if prices[item_id][DODIXIE].sell else 'N/A',
      '{} @ {:,}'.format(STATIONS[buy_from.station], buy_from.sell),
      '{} @ {:,} ({})'.format(STATIONS[sell_at.station], sell_at.sell, '{}%'.format(margin) if margin is not None else 'N/A'),
    ))

  print(DIV)

